//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.DataForm.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.DataForm.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building node &apos;{0}&apos;....
        /// </summary>
        internal static string FormBuilderBuildNodeStart {
            get {
                return ResourceManager.GetString("FormBuilderBuildNodeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing document..
        /// </summary>
        internal static string PreprocessorFinished {
            get {
                return ResourceManager.GetString("PreprocessorFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite recursion detected. Please check layout files and included &lt;link/&gt; elements. All remaining &lt;link/&gt; elements will be ignored by the parser..
        /// </summary>
        internal static string PreprocessorInfiniteRecursionDetectedError {
            get {
                return ResourceManager.GetString("PreprocessorInfiniteRecursionDetectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing pass {0} (of {1} max)....
        /// </summary>
        internal static string PreprocessorPass {
            get {
                return ResourceManager.GetString("PreprocessorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing known attribute &apos;{0}&apos;. The value will not be used..
        /// </summary>
        internal static string ReadKnownAttributeError {
            get {
                return ResourceManager.GetString("ReadKnownAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetData: Error while setting value &apos;{0}&apos; to property {1} from data!.
        /// </summary>
        internal static string SetDataSingleError {
            get {
                return ResourceManager.GetString("SetDataSingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve linked XML file &apos;{0}&apos; because of an error..
        /// </summary>
        internal static string XmlLinkFileResolveError {
            get {
                return ResourceManager.GetString("XmlLinkFileResolveError", resourceCulture);
            }
        }
    }
}
