//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.DataForm.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.DataForm.Library.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte die ItemsSource-Eigenschaft &apos;{0}&apos; nicht finden für Eigenschaft &apos;{1}&apos;!.
        /// </summary>
        internal static string DE_CouldNotFindItemsSourceProperty {
            get {
                return ResourceManager.GetString("DE_CouldNotFindItemsSourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur &apos;table&apos; ist als direktes Kindelement erlaubt!.
        /// </summary>
        internal static string DE_InvalidRootChildNode {
            get {
                return ResourceManager.GetString("DE_InvalidRootChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Element &apos;{0}&apos; nicht erstellen! Das Layout ist ungültig..
        /// </summary>
        internal static string DE_NoFactoryFoundForGivenToken {
            get {
                return ResourceManager.GetString("DE_NoFactoryFoundForGivenToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Kein Label).
        /// </summary>
        internal static string DE_NoLabelText {
            get {
                return ResourceManager.GetString("DE_NoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte die Eigenschaft &apos;{0}&apos; nicht finden auf dem Objekt des Typs &apos;{1}&apos;!.
        /// </summary>
        internal static string DE_PropertyNotFoundOnInstance {
            get {
                return ResourceManager.GetString("DE_PropertyNotFoundOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut validieren.
        /// </summary>
        internal static string DE_RetriggerValidation {
            get {
                return ResourceManager.GetString("DE_RetriggerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribut &apos;text&apos; nicht gesetzt..
        /// </summary>
        internal static string DE_StaticElementNoTextSet {
            get {
                return ResourceManager.GetString("DE_StaticElementNoTextSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden Fehler gefunden, die behoben werden müssen..
        /// </summary>
        internal static string DE_ValidationErrorsFound {
            get {
                return ResourceManager.GetString("DE_ValidationErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find ItemsSource-property &apos;{0}&apos; for property &apos;{1}&apos;!.
        /// </summary>
        internal static string EN_CouldNotFindItemsSourceProperty {
            get {
                return ResourceManager.GetString("EN_CouldNotFindItemsSourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;table&apos; is allowed to be nested directly at root-level!.
        /// </summary>
        internal static string EN_InvalidRootChildNode {
            get {
                return ResourceManager.GetString("EN_InvalidRootChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create element &apos;{0}&apos;! The layout appears to be invalid..
        /// </summary>
        internal static string EN_NoFactoryFoundForGivenToken {
            get {
                return ResourceManager.GetString("EN_NoFactoryFoundForGivenToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No label).
        /// </summary>
        internal static string EN_NoLabelText {
            get {
                return ResourceManager.GetString("EN_NoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found specified property &apos;{0}&apos; on instance of object &apos;{1}&apos;!.
        /// </summary>
        internal static string EN_PropertyNotFoundOnInstance {
            get {
                return ResourceManager.GetString("EN_PropertyNotFoundOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate again.
        /// </summary>
        internal static string EN_RetriggerValidation {
            get {
                return ResourceManager.GetString("EN_RetriggerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;text&apos; attrib not set..
        /// </summary>
        internal static string EN_StaticElementNoTextSet {
            get {
                return ResourceManager.GetString("EN_StaticElementNoTextSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were warnings during validation which need to be fixed..
        /// </summary>
        internal static string EN_ValidationErrorsFound {
            get {
                return ResourceManager.GetString("EN_ValidationErrorsFound", resourceCulture);
            }
        }
    }
}
